# Generated by Django 2.2.12 on 2020-05-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_imagemodel_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='asd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asd', models.CharField(max_length=35, verbose_name='asd')),
            ],
        ),
    ]
