# Generated by Django 2.2.12 on 2020-05-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_asd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asd',
        ),
    ]
