# Generated by Django 2.2.12 on 2020-05-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_delete_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baker',
            name='baker_dateofstart',
        ),
    ]
