# Generated by Django 2.2.12 on 2020-05-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_baker_baker_dateofstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='baker',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='authentication.Baker'),
            preserve_default=False,
        ),
    ]
