# Generated by Django 2.2.12 on 2020-05-31 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_catalog_baker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='baker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
