# Generated by Django 2.2.12 on 2020-05-31 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20200531_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order_id',
            new_name='order',
        ),
    ]
