# Generated by Django 2.2.12 on 2020-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20200531_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'In review'), (2, 'Accepted'), (3, 'Rejected')], default=1, verbose_name='Статус'),
        ),
    ]
