# Generated by Django 2.2.12 on 2020-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_auto_20200603_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
